#!/bin/sh

# Vérification nombre de paramètres
if [ $# -eq 0 ]; then
    ville="Toulouse"
else
    ville=$1
fi

# Exportation des données brutes dans un fichier .txt
curl -s wttr.in/$ville?format=j2 > local.txt

# Récupération de la température actuelle
tempact=$(curl -s wttr.in/$ville?format="%t")
if [ "${tempact:0:1}" = "+" ]; then
    tempact=$(echo $tempact | cut -c 2-)
fi

# Récupération de la température du lendemain
templen=$(head -n 103 local.txt | tail -n 1 | grep -oE "\-*[0-9]*")°C

# Récupération de l'heure et de la date
heure=$(date +"%H:%M")
date=$(date +"%Y-%m-%d")


# Création du fichier d'historique journalier
nom_fichier="meteo_$(date +%d-%m-%Y).txt"
echo "$date - $heure - $ville : $tempact - $templen" >> "$nom_fichier"

# Écriture également dans le fichier meteo.txt pour suivi global
echo "$date - $heure - $ville : $tempact - $templen" >> meteo.txt

exit 0
